query DotcomUserQuery {
  currentUser {
    id
    username
    codyProEnabled
    codyCurrentPeriodCodeUsage
    codyCurrentPeriodChatUsage
    codyCurrentPeriodCodeLimit
    codyCurrentPeriodChatLimit
    completionsQuotaOverride
    codeCompletionsQuotaOverride
  }
}
