{
  repository(name: "%s") {
    commit(rev: "%s") {
      blob(path: "%s") {
        name
        path
        lsif {
          definitions(line: 115, character: 8) {
            nodes {
              url
              resource {
                path
              }
              range {
                start {
                  line
                  character
                }
                end {
                  line
                  character
                }
              }
            }
          }
        }
      }
    }
  }

  search(
    patternType: regexp
    query: "repo:^github.com/neovim/neovim$@HEAD type:symbol patternType:regexp ^nlua_traverse_table$"
  ) {
    results {
      results {
        __typename
        ... on FileMatch {
          ...SymbolFields
        }
      }
    }
  }
}
